# Generated by Django 5.2.8 on 2026-01-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.CharField(choices=[('admin', 'Administrador'), ('reporter', 'Repórter'), ('estagiario', 'Estagiário')], default='estagiario', max_length=20),
        ),
    ]
